extends Node
class_name EventLog

## The Backbone: Every significant game event is logged here.
## HR Reports and Reviews are generated by parsing this log.

signal event_logged(event_data)

var logs = [] # Array of dictionaries: { "time": float, "event": String, "value": float, "detail": String }

func log_event(event_name: String, value: float = 0.0, detail: String = ""):
	var entry = {
		"time": Time.get_ticks_msec(),
		"event": event_name,
		"value": value,
		"detail": detail
	}
	logs.append(entry)
	event_logged.emit(entry)
	# print("LOG: ", event_name, " | ", detail)

func get_events_by_type(event_name: String) -> Array:
	var filtered = []
	for entry in logs:
		if entry["event"] == event_name:
			filtered.append(entry)
	return filtered

func get_save_data() -> Dictionary:
	return {"logs": logs.duplicate(true)}

func load_save_data(data: Dictionary) -> void:
	logs = data.get("logs", []).duplicate(true)

func clear_log():
	logs.clear()
