extends SceneTree

func _initialize():
	call_deferred("_run_check")

func _run_check():
	var main_scene = load("res://scenes/world/Main.tscn")
	_assert(main_scene != null, "Main scene loads")
	var main = main_scene.instantiate()
	root.add_child(main)
	await process_frame
	await process_frame

	var shift_results = root.get_node_or_null("ShiftResultManager")
	var save_system = root.get_node_or_null("SaveSystem")
	var order_manager = root.get_node_or_null("OrderManager")
	var beef = root.get_node_or_null("BeefManager")
	var wallet = root.get_node_or_null("WalletManager")
	var career = root.get_node_or_null("CareerManager")
	var daily = root.find_child("DailyTaskManager", true, false)
	var store_ops = root.find_child("StoreOpsDirector", true, false)
	var staff = root.find_child("StaffDirector", true, false)
	var player = root.find_child("Player", true, false)
	var sauce = root.find_child("SauceStockStation", true, false)
	var bagging = root.find_child("BaggingTableStation", true, false)
	var cleaning = root.find_child("CleaningStation", true, false)
	var recovery = root.find_child("RecoveryStation", true, false)
	var event_log = root.get_node_or_null("EventLog")

	_assert(shift_results != null, "ShiftResultManager autoload exists")
	_assert(save_system != null, "SaveSystem autoload exists")
	_assert(order_manager != null, "OrderManager autoload exists")
	_assert(beef != null, "BeefManager autoload exists")
	_assert(wallet != null and career != null, "Progression autoloads exist")
	_assert(daily != null and store_ops != null and staff != null, "Gameplay directors exist")
	_assert(player != null, "Player spawned")
	_assert(sauce != null and bagging != null and cleaning != null and recovery != null, "Playable task stations exist")
	_assert(event_log != null, "EventLog autoload exists")

	shift_results.begin_shift_snapshot()
	sauce.interact(player)
	bagging.interact(player)
	cleaning.interact(player)
	store_ops.trigger_minor_issue("fryer_timer_drift")
	recovery.interact(player)
	staff.dialogue_for("riley", "rush")
	order_manager.generate_new_order()
	order_manager.fulfill_order(true)
	order_manager.generate_new_order()
	order_manager.fulfill_order(false)
	beef.increase_beef(30.0, "phase7 runtime impatient guest")

	var report = shift_results.complete_shift({"cash": wallet.balance, "completed": order_manager.orders_completed})
	var result = shift_results.get_last_result_data()
	var next_shift = shift_results.get_next_shift_setup()
	var save_data = save_system.get_last_save_data()

	_assert(report.contains("Money Earned:"), "Report includes money earned")
	_assert(report.contains("XP Earned:"), "Report includes XP earned")
	_assert(report.contains("Tips:"), "Report includes tips")
	_assert(report.contains("Customers Served:"), "Report includes customers served")
	_assert(report.contains("Order Accuracy:"), "Report includes order accuracy")
	_assert(report.contains("Average Wait:"), "Report includes average wait")
	_assert(report.contains("Average Patience:"), "Report includes average patience")
	_assert(report.contains("Beef Incidents:"), "Report includes Beef incidents")
	_assert(report.contains("Staff Morale Change:"), "Report includes staff morale change")
	_assert(report.contains("Manager Trust Change:"), "Report includes manager trust change")
	_assert(report.contains("Corporate Approval Change:"), "Report includes corporate approval change")
	_assert(report.contains("Daily Tasks:"), "Report includes daily task summary")
	_assert(report.contains("Reviews:"), "Report includes reviews")
	_assert(report.contains("Write-ups or Warnings:"), "Report includes warnings")
	_assert(report.contains("Funniest/Most Notable Moment:"), "Report includes notable moment")
	_assert(float(result.get("money_earned", 0.0)) > 0.0, "Result tracks earned money")
	_assert(float(result.get("xp_earned", 0.0)) > 0.0, "Result tracks earned XP")
	_assert(int(result.get("tips", 0)) > 0, "Result tracks tips")
	_assert(int(result.get("customers_served", 0)) >= 1, "Result tracks customers served")
	_assert(float(result.get("order_accuracy", 0.0)) < 1.0, "Result tracks imperfect order accuracy")
	_assert(int(result.get("beef_incidents", 0)) >= 1, "Result tracks Beef incidents")
	_assert(int(result.get("daily_tasks_completed", 0)) >= 4, "Result tracks completed daily tasks")
	_assert(result.get("reviews", []).size() >= 1, "Result generates reviews")
	_assert(result.get("unlock_hooks", []).size() >= 1, "Result generates progression unlock hooks")
	_assert(str(result.get("fail_state", "")) != "", "Result generates recoverable fail state field")
	_assert(not next_shift.is_empty(), "Next-shift setup generated")
	_assert(int(next_shift.get("shift_number", 0)) >= 2, "Next-shift number advances")
	_assert(save_system.verify_save_roundtrip(), "Save roundtrip verifies locally")
	_assert(save_data.has("last_shift") and save_data.has("next_shift"), "Save includes last and next shift data")
	_assert(event_log.get_events_by_type("shift_results_generated").size() >= 1, "Shift result event logged")
	_assert(event_log.get_events_by_type("next_shift_prepared").size() >= 1, "Next-shift event logged")

	print("[PASS] Phase 7 runtime shift results/save/replay check passed")
	main.queue_free()
	await process_frame
	quit(0)

func _assert(condition: bool, message: String):
	if condition:
		print("[PASS] " + message)
	else:
		push_error("[FAIL] " + message)
		quit(1)
